name: Deploy and Restart Flask
on:
  workflow_dispatch:

jobs:
  build:
    name: Release and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Move files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "."
          strip_components: 0
          target: "flaskFleetTools"
      - name: Add in DB Credentials
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd urnextroute
            sed -i 's#app.secret_key = 'very_secret_key'#app.secret_key = '{{ secrets.SESSION }}'#g' app.py
      - name: Restart flask
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo ${{ secrets.PASSWORD }} | sudo -S systemctl restart flaskFleetTools
